import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header.jsx'
import Delivery from '../components/HomePage/Delivery'
import Work from '../components/HomePage/Work'
import AboutUs from '../components/HomePage/AboutUs'
import Footer from '../components/HomePage/Footer'
import { useState } from 'react'
import NavBar from '../components/layout/NavBar'

export default function Home() {
  
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Header />
      <div>
        <Delivery />
        <Work />
        <AboutUs />
      </div>
      <Footer />



    </div>
  )
}
